# Generated by Django 4.2 on 2024-07-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('P', 'Planta'), ('E', 'Eléctrica'), ('R', 'Reptil'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
