# Generated by Django 4.2 on 2024-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('R', 'Reptil'), ('P', 'Planta'), ('F', 'Fuego'), ('T', 'Tierra'), ('E', 'Eléctrica'), ('A', 'Agua')], max_length=30),
        ),
    ]
