# Generated by Django 4.2 on 2024-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('T', 'Tierra'), ('E', 'Eléctrica'), ('R', 'Reptil'), ('F', 'Fuego'), ('A', 'Agua')], max_length=30),
        ),
    ]
