# Generated by Django 4.2 on 2024-08-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('R', 'Reptil'), ('E', 'Eléctrica'), ('T', 'Tierra'), ('P', 'Planta')], max_length=30),
        ),
    ]
